### ISSUE TITLE
Link to edit is to Bookdown repo 

### ISSUE THREAD

**Issue by ilapros** [GDSL-UL/san#1]
In _output.yml I imagine you would want
edit: https://github.com/rstudio/bookdown-demo/edit/master/%s 
to be
edit: https://github.com/GDSL-UL/san/edit/master/%s 
so it links to here 
(I'm spying your notes to implement my own notes)

**Comment by darribas** [comment]
Thanks very much! Yes, I think you're right, great catch! If you want to issue a PR, that'd be most welcome, otherwise, we can fix it at some point.
